# Generated by Django 4.2.3 on 2023-07-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 64 символа', max_length=64, unique=True, verbose_name='Название животного')),
                ('image', models.TextField(help_text='Вставьте сюда ID изображения животного в Telegram или ссылку на изображение', verbose_name='Изображение')),
                ('text', models.TextField(help_text='Вставьте сюда текстовое описание животного (обязательное поле)', verbose_name='Описание')),
                ('anim_url', models.TextField(help_text='Вставьте сюда ссылку на страницу с описанием животного (обязательное поле)', verbose_name='Веб-страница')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Порядковый номер НЕ должен совпадать с каким-либо другим номером вопроса', unique=True, verbose_name='Порядковый номер вопроса')),
                ('text', models.TextField(help_text='Введите здесь текст вопроса (обязательное поле)', verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=64, unique=True, verbose_name='ID пользователя')),
                ('ans_list', models.TextField(help_text='Список ответов пользователя на все вопросы(статистические данные) для отладки бота', verbose_name='Ответы пользователя')),
                ('totem_animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_and_models.animal', verbose_name='Итоговое животное')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Уникальный идентификатор пользователя в Telegram', max_length=64, verbose_name='Идентификатор пользователя')),
                ('username', models.CharField(help_text='Имя пользователя в Telegram, если оно задано', max_length=64, null=True, verbose_name='Имя пользователя')),
                ('text', models.TextField(blank=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_and_models.result', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Введите здесь уникальный идентификатор ответа в формате:<номер вопроса>.<номер ответа>.Например для третьего ответа на второй вопрос идентификатором будет 2.3', max_length=8, unique=True, verbose_name='Идентификатор ответа')),
                ('text', models.TextField(help_text='Введите здесь текст ответа (обязательное поле)', verbose_name='Ответ')),
                ('to_question', models.ForeignKey(help_text='К какому вопросу относится ответ (обязательное поле)', on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='admin_and_models.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
